Plug 'preservim/nerdtree'
Plug 'Raimondi/delimitMate'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'mattn/emmet-vim'
Plug 'lambdalisue/vim-fullscreen'
Plug 'neoclide/coc.nvim', {'branch': 'release'} 
Plug 'sheerun/vim-polyglot'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'doums/darcula'
Plug 'ryanoasis/vim-devicons'
Plug 'tpope/vim-surround'
Plug 'voldikss/vim-floaterm'
