Plug 'preservim/nerdtree'
Plug 'Raimondi/delimitMate'
Plug 'tomasr/molokai'
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'mattn/emmet-vim'
Plug 'tomtom/tcomment_vim'
Plug 'lambdalisue/vim-fullscreen'
Plug 'neoclide/coc.nvim', {'branch': 'release'} 
Plug 'ryanoasis/vim-devicons'
Plug 'sheerun/vim-polyglot'
Plug 'rakr/vim-one'
Plug 'drewtempelmeyer/palenight.vim'
